### ISSUE TITLE
Merge in ORCA

### ISSUE THREAD

**Issue by rushsteve1** [rcos/rcos-data#9]
@Apexal and I have discusses merging in his RPI courses API into this one to increase longevity of that project.

https://github.com/Apexal/orca

Is this something we still want to do? Considering it's basically just a cron job that writes to Postgres, it would fit in the current API stack nicely.

Ultimately this is up to Frank though.

**Comment by Apexal** [comment]
Since it's very snug in its current setup of Heroku, I think I should hold off until the RCOS infrastructure is setup and stable to determine whether or not to migrate it.
